In [74]:
import pandas as pd

In [75]:
df=pd.read_csv("employee_data.csv")

In [88]:
df_customers=pd.DataFrame({
    "customers_id":[1,2,3,4],
    "name":["Adam","Bob","Charlie","Dave"]
})
df_orders=pd.DataFrame({
    "order_id":[101,102,103,104],
    "customers_id":[2,1,4,5],
    "amount":[250,120,300,180]
})
pd.merge(df_customers,df_orders,on="customers_id")
pd.merge(df_customers,df_orders,on="customers_id",how="left")
pd.merge(df_customers,df_orders,on="customers_id",how="right")
pd.merge(df_customers,df_orders,on="customers_id",how="outer")

   customers_id     name  order_id  amount
0             1     Adam     102.0   120.0
1             2      Bob     101.0   250.0
2             3  Charlie       NaN     NaN
3             4     Dave     103.0   300.0
4             5      NaN     104.0   180.0

In [84]:
 df_orders

   order_id  customers_id  amount
0       101             2     250
1       102             1     120
2       103             4     300
3       104             5     180

In [96]:
df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["adam","eve","bob"]
})
df2=pd.DataFrame({
    "id":[4,5,6],
    "name":["charlie","steve","heisnberg"]
})

pd.concat([df1,df2],axis=1)

   id  name  id       name
0   1  adam   4    charlie
1   2   eve   5      steve
2   3   bob   6  heisnberg

In [90]:
df1

   id  name
0   1  adam
1   2   eve
2   3   bob

In [91]:
df2

   id       name
0   4    charlie
1   5      steve
2   6  heisnberg