In [6]:
import requests

In [13]:
URL = "https://stephen-king-api.onrender.com/api/books"
res=requests.get(URL)
json_data=res.json()

In [20]:
import pandas as pd
df=pd.json_normalize(json_data["data"])
df=df[["id","Title","Year","ISBN"]]
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [21]:
import requests
import pandas as pd
URL="https://dogapi.dog/api/v2/breeds"

res=requests.get(URL)
json_data=res.json()
df=pd.json_normalize(json_data["data"])
df

,id,type,attributes.name,attributes.description,attributes.life.max,attributes.life.min,attributes.male_weight.max,attributes.male_weight.min,attributes.female_weight.max,attributes.female_weight.min,attributes.hypoallergenic,relationships.group.data.id,relationships.group.data.type
0,036feed0-da8a-42c9-ab9a-57449b530b13,breed,Affenpinscher,The Affenpinscher is a small and playful breed...,16,14,5,3,5,3,True,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group
1,dd9362cc-52e0-462d-b856-fccdcf24b140,breed,Afghan Hound,The Afghan Hound is a large and elegant breed ...,14,12,27,23,25,20,False,be0147df-7755-4228-b132-2518c0c6d10d,group
2,1460844f-841c-4de8-b788-271aa4d63224,breed,Airedale Terrier,The Airedale Terrier is a large and powerful b...,14,12,23,20,20,18,False,1bbf373b-1937-4e73-9863-45385daa4979,group
3,e7e99424-d514-4b56-9f0c-05736f6dd22d,breed,Akita,"The Akita is a large, muscular dog breed that ...",12,10,60,35,50,35,False,56081cf0-fdf2-4114-9bf7-23a3f5b6af91,group
4,667c7359-a739-4f2b-abb4-98867671e375,breed,Alaskan Klee Kai,The Alaskan Klee Kai is a small to medium-size...,15,12,7,6,7,6,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,095a1856-6506-478d-a7a8-206847d5e702,breed,Wirehaired Vizsla,The Wirehaired Vizsla is a medium-sized breed ...,15,12,30,25,30,25,False,ab110192-e41b-43ff-a630-f7aee156b33a,group
279,c6b12b96-9f53-445b-8f3e-bf867c761dca,breed,Working Kelpie,The Working Kelpie is a medium-sized breed of ...,15,12,20,16,20,16,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
280,43cdadb4-851b-4a3a-99c1-5f63d08d97f8,breed,Xoloitzcuintli,"The Xoloitzcuintli, also known as the Mexican ...",15,12,15,10,15,10,True,7f6ea988-366a-4e20-b4ba-4d04274fea61,group
281,052684bc-a484-4f29-b953-d5ccf6a3d5e6,breed,Yakutian Laika,The Yakutian Laika is a medium-sized breed of ...,15,12,30,18,30,18,False,8000793f-a1ae-4ec4-8d55-ef83f1f644e5,group
282,ce40589c-295a-4259-9e83-711854db8129,breed,Yorkshire Terrier,"The Yorkshire Terrier is a small, intelligent ...",15,12,3,2,3,2,False,f56dc4b1-ba1a-4454-8ce2-bd5d41404a0c,group

In [32]:
import requests
import pandas as pd
URL="https://www.scrapethissite.com/pages/simple/"
res=requests.get(URL)
html=res.text
with open("Scraped_data/p.html", "w", encoding="utf-8") as f:
    f.write(html)

In [38]:
#beautifulSoup
from bs4 import BeautifulSoup
with open("Scraped_data/p.html","r") as f:
    html_content=f.read()
soup=BeautifulSoup(html_content,"lxml")

Requirement already satisfied: lxml in c:\users\rahul shakya\anaconda3\lib\site-packages (5.3.0)

In [73]:
all_h3=soup.find_all("h3")
all_countries=[]
for h3 in all_h3:
    name=h3.get_text(strip=True) 
    # print(h3.find_parent("div")["class"])
    population=h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    all_countries.append([name,population])

In [83]:
import pandas as pd
df=pd.DataFrame(all_countries,columns=["Name","population"])
df.to_csv("clean_data/lean.csv")