In [80]:
import pandas as pd
df=pd.read_csv("IMDB dataset.csv")

In [81]:
df.shape

(50000, 2)

In [82]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [83]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [84]:
df.drop_duplicates(inplace=True)

In [54]:
df.shape

(49582, 2)

In [86]:
df.head

<bound method NDFrame.head of                                                   review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]>

## Preprocessing

# 1.Convverting to lowercase

In [87]:
df["review"]=df["review"].str.lower()

# 2.remove links

In [88]:
import re
# sample_text="abc is the word,abc" #abc => xyz

# new_text=re.sub("abc","xyz",sample_text)

In [89]:
import re

def remove_urls(text):
    return re.sub(r"http\S+", "", str(text))

df["review"] = df["review"].apply(remove_urls)

In [90]:
df.head

<bound method NDFrame.head of                                                   review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]>

# 3. removing punctuation

In [91]:

def remove_punc(text):
    if pd.isna(text):
        return text
    return re.sub(r"[^A-Za-z0-9\s]", "", str(text))

df["review"] = df["review"].apply(remove_punc)

# 4.Removing html

In [92]:
def remove_html(text):
    if pd.isna(text):
        return text
    return re.sub(r"<.*?>", "", str(text)) #. = all, * = 0-10 , ? =non greedyy

df["review"] = df["review"].apply(remove_html)

In [93]:
df.head

<bound method NDFrame.head of                                                   review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production br br the filmin...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]>

# 5.Reemoving the StopWords

In [94]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\Rahul
[nltk_data]     shakya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Rahul
[nltk_data]     shakya\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Rahul
[nltk_data]     shakya\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [95]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [96]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import pandas as pd

stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    if pd.isna(text):
        return ""

    tokens = word_tokenize(str(text))

    filtered_words = [word for word in tokens if word.lower() not in stop_words]

    return " ".join(filtered_words)

df["review"] = df["review"].apply(remove_stopwords)

In [97]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

# 6.stemming

In [98]:
from nltk.stem import PorterStemmer

In [103]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(str(text))

    for word in tokens:
        stemmed_token = ps.stem(word)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [104]:
df.head()

                                              review sentiment
0  one review mention watch 1 oz episod youll hoo...  positive
1  wonder littl product br br film techniqu unass...  positive
2  thought wonder way spend time hot summer weeke...  positive
3  basic there famili littl boy jake think there ...  negative
4  petter mattei love time money visual stun film...  positive

# 7.Encoding

In [106]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [107]:
y=df["sentiment"]

In [108]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

# 8.vectorization

In [109]:
df.head()

                                              review  sentiment
0  one review mention watch 1 oz episod youll hoo...          1
1  wonder littl product br br film techniqu unass...          1
2  thought wonder way spend time hot summer weeke...          1
3  basic there famili littl boy jake think there ...          0
4  petter mattei love time money visual stun film...          1

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=5000)
X=tf.fit_transform(df["review"])

In [116]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4108221 stored elements and shape (49582, 5000)>

In [117]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4108221 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3128)	0.02247657520221819
  (0, 3699)	0.05303260513845461
  (0, 2820)	0.056335152130759465
  (0, 4829)	0.08683810111930414
  (0, 3186)	0.4779748736819869
  (0, 1548)	0.11363113782724443
  (0, 4988)	0.05847487708069967
  (0, 2188)	0.07920428628671745
  (0, 3722)	0.09124430218990189
  (0, 1596)	0.061875116936704874
  (0, 2067)	0.045550371261069075
  (0, 2800)	0.08207492074377734
  (0, 597)	0.06604637122595439
  (0, 1747)	0.0686964728980499
  (0, 4473)	0.034897814163007954
  (0, 4275)	0.17902125496384533
  (0, 644)	0.07329114041453123
  (0, 3848)	0.03371565199591125
  (0, 4768)	0.25360309572058143
  (0, 3936)	0.044227430566816064
  (0, 4934)	0.0540372278361242
  (0, 1956)	0.03368993773064575
  (0, 4612)	0.07593396995392995
  (0, 3994)	0.14607477308987574
  (0, 2104)	0.05855708556851623
  :	:
  (49581, 2293)	0.10458344189020945
  (49581, 1668)	0.18433226235701797
  (49581, 2215)	0.0900785901824944
  (49581, 4610)	0.10184298129478103
  (49581, 775)	0.11838755189630307
  (49581, 3838)	0.10822308881453009
  (49581, 2530)	0.12260104929248984
  (49581, 4666)	0.1109942891744833
  (49581, 2593)	0.10329243103798556
  (49581, 2363)	0.1559787285652783
  (49581, 382)	0.12347200181171954
  (49581, 2075)	0.1380260527352
  (49581, 3649)	0.11720771925795188
  (49581, 2275)	0.17902191038237042
  (49581, 318)	0.11690727939870121
  (49581, 4590)	0.17288184680556398
  (49581, 2518)	0.19867409797682406
  (49581, 4174)	0.21786526543656748
  (49581, 1093)	0.17325862462405212
  (49581, 682)	0.15983836343432056
  (49581, 3035)	0.17844679708127875
  (49581, 2953)	0.18828409878503496
  (49581, 777)	0.13998019175261842
  (49581, 1972)	0.17098195153620072
  (49581, 3650)	0.16403221176378133

In [118]:
# Dataset & Data Loaders

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test =train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [119]:
import torch
from torch.utils.data import TensorDataset,DataLoader

In [124]:
type(X_test)

scipy.sparse._csr.csr_matrix

In [125]:

X_test=X_test.toarray()
train_set=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values)float()
)